apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: 'http://docker-registry.jx-test.90.84.242.41.nip.io/v2/vlandemaine-orange/jx-test2:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: 'http://docker-registry.jx-test.90.84.242.41.nip.io/v2/vlandemaine-orange/jx-test2:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-test2
        chartPath: charts/jx-test2
        setValueTemplates:
          image.repository: 'http://docker-registry.jx-test.90.84.242.41.nip.io/v2/vlandemaine-orange/jx-test2'
          image.tag: '{{.DIGEST_HEX}}'
